public class Member360Constants {
    public static final String STATUS_ACTIVE = 'Active';
    public static final String STATUS_INACTIVE = 'Inactive';
    public static final String SEGMENT_BASIC = 'Basic';
    public static final String SEGMENT_PREMIUM = 'Premium';
    public static final String SEGMENT_VVIP = 'VVIP';
    public static final String SEGMENT_BUSINESS = 'Business';
    public static final String CURRENCY_TYPE_QUALIFYING = 'Qualifying';
    public static final String ERROR_MEMBER_ID_NULL = 'Member Id cannot be null';
    public static final String ERROR_LOYALTY_MEMBER_ID_REQUIRED = 'Loyalty Program Member Id is required.';
    public static final String ERROR_NO_MEMBER_CURRENCY = 'No qualifying Loyalty Member Currency was found.';
    public static final String ERROR_NO_LOYALTY_TIERS = 'No Loyalty Tiers were found for this tier group.';
    public static final String ERROR_SEGMENT_BLANK = 'Gaming Segment cannot be blank';
    public static final String ERROR_FETCH_MEMBER = 'Unable to fetch member: ';
    public static final String ERROR_UPDATE_SEGMENT = 'Unable to update Gaming Segment: ';
    public static final String ERROR_HOST_USER_REQUIRED = 'Host User is required.';
    public static final Integer QUERY_LIMIT = 1;
}